import Sqpack.S11Opt.Split.U2G.C220.Main
import Sqpack.S11Opt.Split.U2G.C1652.Main
import Sqpack.S11Opt.Split.U2G.C1658.Main
import Sqpack.S11Opt.Split.U2G.C1681.Main
import Sqpack.S11Opt.Split.U2G.C1687.Main
import Sqpack.S11Opt.Split.U2G.C1690.Main
import Sqpack.S11Opt.Split.U2G.C1692.Main
import Sqpack.S11Opt.Split.U2G.C1709.Main
import Sqpack.S11Opt.Split.U2G.C1723.Main
import Sqpack.S11Opt.Split.U2G.C1727.Main
import Sqpack.S11Opt.Split.U2G.C1776.Main
import Sqpack.S11Opt.Split.U2G.C1800.Main
import Sqpack.S11Opt.Split.U2G.C1816.Main
import Sqpack.S11Opt.Split.U2G.C1841.Main
import Sqpack.S11Opt.Split.U2G.C1876.Main
import Sqpack.S11Opt.Split.U2G.C2054.Main
import Sqpack.S11Opt.Split.U2G.C2086.Main
import Sqpack.S11Opt.Split.U2G.C2095.Main
import Sqpack.S11Opt.Split.U2G.C2099.Main
import Sqpack.S11Opt.Split.U2G.C2100.Main
import Sqpack.S11Opt.Split.U2G.C2104.Main
import Sqpack.S11Opt.Split.U2G.C2108.Main
import Sqpack.S11Opt.Split.U2G.C2117.Main
import Sqpack.S11Opt.Split.U2G.C2123.Main
import Sqpack.S11Opt.Split.U2G.C2127.Main
import Sqpack.S11Opt.Split.U2G.C2143.Main
import Sqpack.S11Opt.Split.U2G.C2173.Main

/-!
# U2Generic — the 27 generic cases (PROOF.md §5)

Each case is excluded by the owned-hull induction (`U2Rules`, `U2P/Rules.lean`, `U2P/Branch.lean`)
with box trees written by `scripts/u2p/` (prefix `U2G`); this file collects the per-case
theorems `U2G.C<case>.excluded`.  Generated by `scripts/u2agg/gen_agg.py`.
-/

namespace SquarePacking.S11Opt.Split

/-- **U2 (generic).** -/
theorem generic_excluded : ∀ i ∈ genericIdx, CaseExcluded (maskAt i) := by
  intro i hi
  simp only [genericIdx, List.mem_cons, List.not_mem_nil, or_false] at hi
  rcases hi with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact U2G.C220.excluded
  · exact U2G.C1652.excluded
  · exact U2G.C1658.excluded
  · exact U2G.C1681.excluded
  · exact U2G.C1687.excluded
  · exact U2G.C1690.excluded
  · exact U2G.C1692.excluded
  · exact U2G.C1709.excluded
  · exact U2G.C1723.excluded
  · exact U2G.C1727.excluded
  · exact U2G.C1776.excluded
  · exact U2G.C1800.excluded
  · exact U2G.C1816.excluded
  · exact U2G.C1841.excluded
  · exact U2G.C1876.excluded
  · exact U2G.C2054.excluded
  · exact U2G.C2086.excluded
  · exact U2G.C2095.excluded
  · exact U2G.C2099.excluded
  · exact U2G.C2100.excluded
  · exact U2G.C2104.excluded
  · exact U2G.C2108.excluded
  · exact U2G.C2117.excluded
  · exact U2G.C2123.excluded
  · exact U2G.C2127.excluded
  · exact U2G.C2143.excluded
  · exact U2G.C2173.excluded

end SquarePacking.S11Opt.Split
