import Sqpack.S11Opt.Split.U2P.C221.Main
import Sqpack.S11Opt.Split.U2P.C247.Main
import Sqpack.S11Opt.Split.U2P.C248.Main
import Sqpack.S11Opt.Split.U2P.C250.Main
import Sqpack.S11Opt.Split.U2P.C251.Main
import Sqpack.S11Opt.Split.U2P.C439.Main
import Sqpack.S11Opt.Split.U2P.C455.Main
import Sqpack.S11Opt.Split.U2P.C456.Main
import Sqpack.S11Opt.Split.U2P.C647.Main
import Sqpack.S11Opt.Split.U2P.C649.Main
import Sqpack.S11Opt.Split.U2P.C650.Main
import Sqpack.S11Opt.Split.U2P.C651.Main
import Sqpack.S11Opt.Split.U2P.C652.Main
import Sqpack.S11Opt.Split.U2P.C654.Main
import Sqpack.S11Opt.Split.U2P.C655.Main
import Sqpack.S11Opt.Split.U2P.C656.Main
import Sqpack.S11Opt.Split.U2P.C657.Main
import Sqpack.S11Opt.Split.U2P.C659.Main
import Sqpack.S11Opt.Split.U2P.C660.Main
import Sqpack.S11Opt.Split.U2P.C761.Main
import Sqpack.S11Opt.Split.U2P.C763.Main
import Sqpack.S11Opt.Split.U2P.C778.Main
import Sqpack.S11Opt.Split.U2P.C817.Main
import Sqpack.S11Opt.Split.U2P.C868.Main
import Sqpack.S11Opt.Split.U2P.C877.Main
import Sqpack.S11Opt.Split.U2P.C894.Main
import Sqpack.S11Opt.Split.U2P.C919.Main
import Sqpack.S11Opt.Split.U2P.C926.Main
import Sqpack.S11Opt.Split.U2P.C927.Main
import Sqpack.S11Opt.Split.U2P.C928.Main
import Sqpack.S11Opt.Split.U2P.C929.Main
import Sqpack.S11Opt.Split.U2P.C955.Main
import Sqpack.S11Opt.Split.U2P.C956.Main
import Sqpack.S11Opt.Split.U2P.C958.Main
import Sqpack.S11Opt.Split.U2P.C965.Main
import Sqpack.S11Opt.Split.U2P.C966.Main
import Sqpack.S11Opt.Split.U2P.C970.Main
import Sqpack.S11Opt.Split.U2P.C991.Main
import Sqpack.S11Opt.Split.U2P.C997.Main
import Sqpack.S11Opt.Split.U2P.C998.Main
import Sqpack.S11Opt.Split.U2P.C1000.Main
import Sqpack.S11Opt.Split.U2P.C1001.Main
import Sqpack.S11Opt.Split.U2P.C1012.Main
import Sqpack.S11Opt.Split.U2P.C1013.Main
import Sqpack.S11Opt.Split.U2P.C1025.Main
import Sqpack.S11Opt.Split.U2P.C1026.Main
import Sqpack.S11Opt.Split.U2P.C1049.Main
import Sqpack.S11Opt.Split.U2P.C1054.Main
import Sqpack.S11Opt.Split.U2P.C1060.Main
import Sqpack.S11Opt.Split.U2P.C1067.Main
import Sqpack.S11Opt.Split.U2P.C1069.Main
import Sqpack.S11Opt.Split.U2P.C1070.Main
import Sqpack.S11Opt.Split.U2P.C1075.Main
import Sqpack.S11Opt.Split.U2P.C1076.Main
import Sqpack.S11Opt.Split.U2P.C1079.Main
import Sqpack.S11Opt.Split.U2P.C1083.Main
import Sqpack.S11Opt.Split.U2P.C1107.Main
import Sqpack.S11Opt.Split.U2P.C1108.Main
import Sqpack.S11Opt.Split.U2P.C1109.Main
import Sqpack.S11Opt.Split.U2P.C1110.Main
import Sqpack.S11Opt.Split.U2P.C1111.Main
import Sqpack.S11Opt.Split.U2P.C1112.Main
import Sqpack.S11Opt.Split.U2P.C1114.Main
import Sqpack.S11Opt.Split.U2P.C1115.Main
import Sqpack.S11Opt.Split.U2P.C1124.Main
import Sqpack.S11Opt.Split.U2P.C1125.Main
import Sqpack.S11Opt.Split.U2P.C1128.Main
import Sqpack.S11Opt.Split.U2P.C1143.Main
import Sqpack.S11Opt.Split.U2P.C1383.Main
import Sqpack.S11Opt.Split.U2P.C1839.Main
import Sqpack.S11Opt.Split.U2P.C2174.Main
import Sqpack.S11Opt.Split.U2P.C2175.Main
import Sqpack.S11Opt.Split.U2P.C2176.Main
import Sqpack.S11Opt.Split.U2P.C2178.Main
import Sqpack.S11Opt.Split.U2P.C2182.Main
import Sqpack.S11Opt.Split.U2P.C2183.Main

set_option linter.style.longLine false

/-!
# U2 — prior cases (76; PROOF.md §5)

Owner: f1.  Each case `i` is excluded by `U2P.C<i>.excluded`, an owned-hull induction with box
trees generated by `scripts/u2p/gen_u2p.py` (rules in `U2P/Rules.lean`, branches in
`U2P/Branch.lean`).  The generated files are not in the repository; `scripts/u2p/MANIFEST_prior.sha256`
records their hashes.  Nothing of the author's prior certificates is used.
-/

namespace SquarePacking.S11Opt.Split

/-- **U2 (prior).** -/
theorem prior_excluded : ∀ i ∈ priorIdx, CaseExcluded (maskAt i) := by
  intro i hi
  simp only [priorIdx, List.mem_cons, List.not_mem_nil, or_false] at hi
  rcases hi with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact U2P.C221.excluded
  · exact U2P.C247.excluded
  · exact U2P.C248.excluded
  · exact U2P.C250.excluded
  · exact U2P.C251.excluded
  · exact U2P.C439.excluded
  · exact U2P.C455.excluded
  · exact U2P.C456.excluded
  · exact U2P.C647.excluded
  · exact U2P.C649.excluded
  · exact U2P.C650.excluded
  · exact U2P.C651.excluded
  · exact U2P.C652.excluded
  · exact U2P.C654.excluded
  · exact U2P.C655.excluded
  · exact U2P.C656.excluded
  · exact U2P.C657.excluded
  · exact U2P.C659.excluded
  · exact U2P.C660.excluded
  · exact U2P.C761.excluded
  · exact U2P.C763.excluded
  · exact U2P.C778.excluded
  · exact U2P.C817.excluded
  · exact U2P.C868.excluded
  · exact U2P.C877.excluded
  · exact U2P.C894.excluded
  · exact U2P.C919.excluded
  · exact U2P.C926.excluded
  · exact U2P.C927.excluded
  · exact U2P.C928.excluded
  · exact U2P.C929.excluded
  · exact U2P.C955.excluded
  · exact U2P.C956.excluded
  · exact U2P.C958.excluded
  · exact U2P.C965.excluded
  · exact U2P.C966.excluded
  · exact U2P.C970.excluded
  · exact U2P.C991.excluded
  · exact U2P.C997.excluded
  · exact U2P.C998.excluded
  · exact U2P.C1000.excluded
  · exact U2P.C1001.excluded
  · exact U2P.C1012.excluded
  · exact U2P.C1013.excluded
  · exact U2P.C1025.excluded
  · exact U2P.C1026.excluded
  · exact U2P.C1049.excluded
  · exact U2P.C1054.excluded
  · exact U2P.C1060.excluded
  · exact U2P.C1067.excluded
  · exact U2P.C1069.excluded
  · exact U2P.C1070.excluded
  · exact U2P.C1075.excluded
  · exact U2P.C1076.excluded
  · exact U2P.C1079.excluded
  · exact U2P.C1083.excluded
  · exact U2P.C1107.excluded
  · exact U2P.C1108.excluded
  · exact U2P.C1109.excluded
  · exact U2P.C1110.excluded
  · exact U2P.C1111.excluded
  · exact U2P.C1112.excluded
  · exact U2P.C1114.excluded
  · exact U2P.C1115.excluded
  · exact U2P.C1124.excluded
  · exact U2P.C1125.excluded
  · exact U2P.C1128.excluded
  · exact U2P.C1143.excluded
  · exact U2P.C1383.excluded
  · exact U2P.C1839.excluded
  · exact U2P.C2174.excluded
  · exact U2P.C2175.excluded
  · exact U2P.C2176.excluded
  · exact U2P.C2178.excluded
  · exact U2P.C2182.excluded
  · exact U2P.C2183.excluded

end SquarePacking.S11Opt.Split
