import Sqpack.S11Opt.Split.U4.Cert0
import Sqpack.S11Opt.Split.U4.Cert1
import Sqpack.S11Opt.Split.U4.Cert2
import Sqpack.S11Opt.Split.U4.Cert3
import Sqpack.S11Opt.Split.U4.Cert4
import Sqpack.S11Opt.Split.U4.Cert5
import Sqpack.S11Opt.Split.U4.Cert6
import Sqpack.S11Opt.Split.U4.Cert7

/-! Generated by `scripts/u4/gen_lean.py`.  Do not edit by hand. -/

namespace SquarePacking.S11Opt.Split.U4

/-- The certificates of every branch. -/
def certList : List (List (List ℕ)) := [cb0, cb1, cb2, cb3, cb4, cb5, cb6, cb7, cb8, cb9, cb10, cb11, cb12, cb13, cb14, cb15, cb16, cb17, cb18, cb19, cb20, cb21, cb22, cb23, cb24, cb25, cb26, cb27, cb28, cb29, cb30, cb31, cb32, cb33, cb34, cb35, cb36, cb37, cb38, cb39, cb40, cb41, cb42, cb43, cb44, cb45, cb46, cb47, cb48, cb49, cb50, cb51, cb52, cb53, cb54, cb55, cb56, cb57, cb58, cb59, cb60, cb61, cb62, cb63, cb64, cb65, cb66, cb67, cb68, cb69, cb70, cb71, cb72, cb73, cb74, cb75, cb76, cb77, cb78, cb79, cb80, cb81, cb82, cb83, cb84, cb85, cb86, cb87, cb88, cb89, cb90, cb91, cb92, cb93, cb94, cb95, cb96, cb97, cb98, cb99, cb100, cb101, cb102, cb103, cb104, cb105, cb106, cb107, cb108, cb109, cb110, cb111, cb112, cb113, cb114, cb115, cb116, cb117, cb118, cb119, cb120, cb121, cb122, cb123, cb124, cb125, cb126, cb127]

theorem all_branches :
    ∀ bi < branches.length, branchOK rowsD kts rI (branches.getD bi []) (certList.getD bi []) = true := by
  intro bi hbi
  have hlen : branches.length = 128 := rfl
  rw [hlen] at hbi
  interval_cases bi
  · exact cb0_ok
  · exact cb1_ok
  · exact cb2_ok
  · exact cb3_ok
  · exact cb4_ok
  · exact cb5_ok
  · exact cb6_ok
  · exact cb7_ok
  · exact cb8_ok
  · exact cb9_ok
  · exact cb10_ok
  · exact cb11_ok
  · exact cb12_ok
  · exact cb13_ok
  · exact cb14_ok
  · exact cb15_ok
  · exact cb16_ok
  · exact cb17_ok
  · exact cb18_ok
  · exact cb19_ok
  · exact cb20_ok
  · exact cb21_ok
  · exact cb22_ok
  · exact cb23_ok
  · exact cb24_ok
  · exact cb25_ok
  · exact cb26_ok
  · exact cb27_ok
  · exact cb28_ok
  · exact cb29_ok
  · exact cb30_ok
  · exact cb31_ok
  · exact cb32_ok
  · exact cb33_ok
  · exact cb34_ok
  · exact cb35_ok
  · exact cb36_ok
  · exact cb37_ok
  · exact cb38_ok
  · exact cb39_ok
  · exact cb40_ok
  · exact cb41_ok
  · exact cb42_ok
  · exact cb43_ok
  · exact cb44_ok
  · exact cb45_ok
  · exact cb46_ok
  · exact cb47_ok
  · exact cb48_ok
  · exact cb49_ok
  · exact cb50_ok
  · exact cb51_ok
  · exact cb52_ok
  · exact cb53_ok
  · exact cb54_ok
  · exact cb55_ok
  · exact cb56_ok
  · exact cb57_ok
  · exact cb58_ok
  · exact cb59_ok
  · exact cb60_ok
  · exact cb61_ok
  · exact cb62_ok
  · exact cb63_ok
  · exact cb64_ok
  · exact cb65_ok
  · exact cb66_ok
  · exact cb67_ok
  · exact cb68_ok
  · exact cb69_ok
  · exact cb70_ok
  · exact cb71_ok
  · exact cb72_ok
  · exact cb73_ok
  · exact cb74_ok
  · exact cb75_ok
  · exact cb76_ok
  · exact cb77_ok
  · exact cb78_ok
  · exact cb79_ok
  · exact cb80_ok
  · exact cb81_ok
  · exact cb82_ok
  · exact cb83_ok
  · exact cb84_ok
  · exact cb85_ok
  · exact cb86_ok
  · exact cb87_ok
  · exact cb88_ok
  · exact cb89_ok
  · exact cb90_ok
  · exact cb91_ok
  · exact cb92_ok
  · exact cb93_ok
  · exact cb94_ok
  · exact cb95_ok
  · exact cb96_ok
  · exact cb97_ok
  · exact cb98_ok
  · exact cb99_ok
  · exact cb100_ok
  · exact cb101_ok
  · exact cb102_ok
  · exact cb103_ok
  · exact cb104_ok
  · exact cb105_ok
  · exact cb106_ok
  · exact cb107_ok
  · exact cb108_ok
  · exact cb109_ok
  · exact cb110_ok
  · exact cb111_ok
  · exact cb112_ok
  · exact cb113_ok
  · exact cb114_ok
  · exact cb115_ok
  · exact cb116_ok
  · exact cb117_ok
  · exact cb118_ok
  · exact cb119_ok
  · exact cb120_ok
  · exact cb121_ok
  · exact cb122_ok
  · exact cb123_ok
  · exact cb124_ok
  · exact cb125_ok
  · exact cb126_ok
  · exact cb127_ok

end SquarePacking.S11Opt.Split.U4
