import Sqpack.S11Opt.Split.U4.RowsT
import Sqpack.S11Opt.Split.U4.RowsW
import Sqpack.S11Opt.Split.U4.RowsU0
import Sqpack.S11Opt.Split.U4.RowsU1
import Sqpack.S11Opt.Split.U4.RowsU2
import Sqpack.S11Opt.Split.U4.RowsU3

/-! Generated by `scripts/u4/gen_lean.py`.  Do not edit by hand. -/

set_option maxHeartbeats 4000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.style.longLine false

open Real SquarePacking.S11Opt

namespace SquarePacking.S11Opt.Split.U4

lemma featA_6_0_2 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 6) (c 0) (θ 6 + 2 * (π / 2)) (θ 0)) :
    ∀ id ∈ (featRows.getD 0 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 0 []).getD 0 [] = [20] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl
  · exact row_6_0_2_pp H hF.1

lemma pair_0 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 0) (θ 0) 1) (sqInt (c 6) (θ 6) 1)) :
    ∃ t < (featRows.getD 0 []).length, ∀ id ∈ (featRows.getD 0 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_0_6_0 H)
    · exact absurd h4 (featU_0_6_1 H)
    · exact absurd h4 (featU_0_6_2 H)
    · exact absurd h4 (featU_0_6_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_6_0_0 H)
    · exact absurd h4 (featU_6_0_1 H)
    · exact ⟨0, by decide, featA_6_0_2 H h4⟩
    · exact absurd h4 (featU_6_0_3 H)

lemma featA_9_1_3 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 9) (c 1) (θ 9 + 3 * (π / 2)) (θ 1)) :
    ∀ id ∈ (featRows.getD 1 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 1 []).getD 0 [] = [21] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl
  · exact row_9_1_3_mp H hF.2.2.1

lemma pair_1 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 1) (θ 1) 1) (sqInt (c 9) (θ 9) 1)) :
    ∃ t < (featRows.getD 1 []).length, ∀ id ∈ (featRows.getD 1 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_1_9_0 H)
    · exact absurd h4 (featU_1_9_1 H)
    · exact absurd h4 (featU_1_9_2 H)
    · exact absurd h4 (featU_1_9_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_9_1_0 H)
    · exact absurd h4 (featU_9_1_1 H)
    · exact absurd h4 (featU_9_1_2 H)
    · exact ⟨0, by decide, featA_9_1_3 H h4⟩

lemma featA_8_2_0 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 8) (c 2) (θ 8 + 0 * (π / 2)) (θ 2)) :
    ∀ id ∈ (featRows.getD 2 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 2 []).getD 0 [] = [22] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl
  · exact row_8_2_0_mm H hF.2.2.2

lemma pair_2 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 2) (θ 2) 1) (sqInt (c 8) (θ 8) 1)) :
    ∃ t < (featRows.getD 2 []).length, ∀ id ∈ (featRows.getD 2 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_2_8_0 H)
    · exact absurd h4 (featU_2_8_1 H)
    · exact absurd h4 (featU_2_8_2 H)
    · exact absurd h4 (featU_2_8_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact ⟨0, by decide, featA_8_2_0 H h4⟩
    · exact absurd h4 (featU_8_2_1 H)
    · exact absurd h4 (featU_8_2_2 H)
    · exact absurd h4 (featU_8_2_3 H)

lemma featA_10_2_1 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 10) (c 2) (θ 10 + 1 * (π / 2)) (θ 2)) :
    ∀ id ∈ (featRows.getD 3 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 3 []).getD 0 [] = [23] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl
  · exact row_10_2_1_pm H hF.2.1

lemma pair_3 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 2) (θ 2) 1) (sqInt (c 10) (θ 10) 1)) :
    ∃ t < (featRows.getD 3 []).length, ∀ id ∈ (featRows.getD 3 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_2_10_0 H)
    · exact absurd h4 (featU_2_10_1 H)
    · exact absurd h4 (featU_2_10_2 H)
    · exact absurd h4 (featU_2_10_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_10_2_0 H)
    · exact ⟨0, by decide, featA_10_2_1 H h4⟩
    · exact absurd h4 (featU_10_2_2 H)
    · exact absurd h4 (featU_10_2_3 H)

lemma featA_3_4_0 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 3) (c 4) (θ 3 + 0 * (π / 2)) (θ 4)) :
    ∀ id ∈ (featRows.getD 4 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 4 []).getD 0 [] = [24, 25] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_3_4_0_mp H hF.2.2.1
  · exact row_3_4_0_mm H hF.2.2.2

lemma featA_4_3_2 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 4) (c 3) (θ 4 + 2 * (π / 2)) (θ 3)) :
    ∀ id ∈ (featRows.getD 4 []).getD 1 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 4 []).getD 1 [] = [24, 25] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_4_3_2_pp H hF.1
  · exact row_4_3_2_pm H hF.2.1

lemma pair_4 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 3) (θ 3) 1) (sqInt (c 4) (θ 4) 1)) :
    ∃ t < (featRows.getD 4 []).length, ∀ id ∈ (featRows.getD 4 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact ⟨0, by decide, featA_3_4_0 H h4⟩
    · exact absurd h4 (featU_3_4_1 H)
    · exact absurd h4 (featU_3_4_2 H)
    · exact absurd h4 (featU_3_4_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_4_3_0 H)
    · exact absurd h4 (featU_4_3_1 H)
    · exact ⟨1, by decide, featA_4_3_2 H h4⟩
    · exact absurd h4 (featU_4_3_3 H)

lemma featA_3_5_3 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 3) (c 5) (θ 3 + 3 * (π / 2)) (θ 5)) :
    ∀ id ∈ (featRows.getD 5 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 5 []).getD 0 [] = [26, 27] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_3_5_3_pp H hF.1
  · exact row_3_5_3_mp H hF.2.2.1

lemma featA_5_3_1 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 5) (c 3) (θ 5 + 1 * (π / 2)) (θ 3)) :
    ∀ id ∈ (featRows.getD 5 []).getD 1 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 5 []).getD 1 [] = [26, 27] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_5_3_1_pm H hF.2.1
  · exact row_5_3_1_mm H hF.2.2.2

lemma pair_5 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 3) (θ 3) 1) (sqInt (c 5) (θ 5) 1)) :
    ∃ t < (featRows.getD 5 []).length, ∀ id ∈ (featRows.getD 5 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_3_5_0 H)
    · exact absurd h4 (featU_3_5_1 H)
    · exact absurd h4 (featU_3_5_2 H)
    · exact ⟨0, by decide, featA_3_5_3 H h4⟩
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_5_3_0 H)
    · exact ⟨1, by decide, featA_5_3_1 H h4⟩
    · exact absurd h4 (featU_5_3_2 H)
    · exact absurd h4 (featU_5_3_3 H)

lemma featA_4_5_2 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 4) (c 5) (θ 4 + 2 * (π / 2)) (θ 5)) :
    ∀ id ∈ (featRows.getD 6 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 6 []).getD 0 [] = [28, 29] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_4_5_2_pp H hF.1
  · exact row_4_5_2_pm H hF.2.1

lemma featA_4_5_3 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 4) (c 5) (θ 4 + 3 * (π / 2)) (θ 5)) :
    ∀ id ∈ (featRows.getD 6 []).getD 1 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 6 []).getD 1 [] = [30, 31] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_4_5_3_pp H hF.1
  · exact row_4_5_3_mp H hF.2.2.1

lemma featA_5_4_0 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 5) (c 4) (θ 5 + 0 * (π / 2)) (θ 4)) :
    ∀ id ∈ (featRows.getD 6 []).getD 2 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 6 []).getD 2 [] = [32, 28] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_5_4_0_mp H hF.2.2.1
  · exact row_5_4_0_mm H hF.2.2.2

lemma featA_5_4_1 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 5) (c 4) (θ 5 + 1 * (π / 2)) (θ 4)) :
    ∀ id ∈ (featRows.getD 6 []).getD 3 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 6 []).getD 3 [] = [33, 30] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_5_4_1_pm H hF.2.1
  · exact row_5_4_1_mm H hF.2.2.2

lemma pair_6 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 4) (θ 4) 1) (sqInt (c 5) (θ 5) 1)) :
    ∃ t < (featRows.getD 6 []).length, ∀ id ∈ (featRows.getD 6 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_4_5_0 H)
    · exact absurd h4 (featU_4_5_1 H)
    · exact ⟨0, by decide, featA_4_5_2 H h4⟩
    · exact ⟨1, by decide, featA_4_5_3 H h4⟩
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact ⟨2, by decide, featA_5_4_0 H h4⟩
    · exact ⟨3, by decide, featA_5_4_1 H h4⟩
    · exact absurd h4 (featU_5_4_2 H)
    · exact absurd h4 (featU_5_4_3 H)

lemma featA_8_4_1 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 8) (c 4) (θ 8 + 1 * (π / 2)) (θ 4)) :
    ∀ id ∈ (featRows.getD 7 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 7 []).getD 0 [] = [34] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl
  · exact row_8_4_1_pm H hF.2.1

lemma pair_7 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 4) (θ 4) 1) (sqInt (c 8) (θ 8) 1)) :
    ∃ t < (featRows.getD 7 []).length, ∀ id ∈ (featRows.getD 7 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_4_8_0 H)
    · exact absurd h4 (featU_4_8_1 H)
    · exact absurd h4 (featU_4_8_2 H)
    · exact absurd h4 (featU_4_8_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_8_4_0 H)
    · exact ⟨0, by decide, featA_8_4_1 H h4⟩
    · exact absurd h4 (featU_8_4_2 H)
    · exact absurd h4 (featU_8_4_3 H)

lemma featA_6_5_1 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 6) (c 5) (θ 6 + 1 * (π / 2)) (θ 5)) :
    ∀ id ∈ (featRows.getD 8 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 8 []).getD 0 [] = [35] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl
  · exact row_6_5_1_pm H hF.2.1

lemma pair_8 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 5) (θ 5) 1) (sqInt (c 6) (θ 6) 1)) :
    ∃ t < (featRows.getD 8 []).length, ∀ id ∈ (featRows.getD 8 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_5_6_0 H)
    · exact absurd h4 (featU_5_6_1 H)
    · exact absurd h4 (featU_5_6_2 H)
    · exact absurd h4 (featU_5_6_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_6_5_0 H)
    · exact ⟨0, by decide, featA_6_5_1 H h4⟩
    · exact absurd h4 (featU_6_5_2 H)
    · exact absurd h4 (featU_6_5_3 H)

lemma featA_6_7_3 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 6) (c 7) (θ 6 + 3 * (π / 2)) (θ 7)) :
    ∀ id ∈ (featRows.getD 9 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 9 []).getD 0 [] = [36, 37] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_6_7_3_pp H hF.1
  · exact row_6_7_3_mp H hF.2.2.1

lemma featA_7_6_1 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 7) (c 6) (θ 7 + 1 * (π / 2)) (θ 6)) :
    ∀ id ∈ (featRows.getD 9 []).getD 1 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 9 []).getD 1 [] = [38, 39] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_7_6_1_pm H hF.2.1
  · exact row_7_6_1_mm H hF.2.2.2

lemma pair_9 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 6) (θ 6) 1) (sqInt (c 7) (θ 7) 1)) :
    ∃ t < (featRows.getD 9 []).length, ∀ id ∈ (featRows.getD 9 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_6_7_0 H)
    · exact absurd h4 (featU_6_7_1 H)
    · exact absurd h4 (featU_6_7_2 H)
    · exact ⟨0, by decide, featA_6_7_3 H h4⟩
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_7_6_0 H)
    · exact ⟨1, by decide, featA_7_6_1 H h4⟩
    · exact absurd h4 (featU_7_6_2 H)
    · exact absurd h4 (featU_7_6_3 H)

lemma featA_6_8_0 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 6) (c 8) (θ 6 + 0 * (π / 2)) (θ 8)) :
    ∀ id ∈ (featRows.getD 10 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 10 []).getD 0 [] = [40, 41] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_6_8_0_mp H hF.2.2.1
  · exact row_6_8_0_mm H hF.2.2.2

lemma featA_8_6_2 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 8) (c 6) (θ 8 + 2 * (π / 2)) (θ 6)) :
    ∀ id ∈ (featRows.getD 10 []).getD 1 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 10 []).getD 1 [] = [42, 43] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_8_6_2_pp H hF.1
  · exact row_8_6_2_pm H hF.2.1

lemma pair_10 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 6) (θ 6) 1) (sqInt (c 8) (θ 8) 1)) :
    ∃ t < (featRows.getD 10 []).length, ∀ id ∈ (featRows.getD 10 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact ⟨0, by decide, featA_6_8_0 H h4⟩
    · exact absurd h4 (featU_6_8_1 H)
    · exact absurd h4 (featU_6_8_2 H)
    · exact absurd h4 (featU_6_8_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_8_6_0 H)
    · exact absurd h4 (featU_8_6_1 H)
    · exact ⟨1, by decide, featA_8_6_2 H h4⟩
    · exact absurd h4 (featU_8_6_3 H)

lemma featA_7_9_0 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 7) (c 9) (θ 7 + 0 * (π / 2)) (θ 9)) :
    ∀ id ∈ (featRows.getD 11 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 11 []).getD 0 [] = [44, 45] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_7_9_0_mp H hF.2.2.1
  · exact row_7_9_0_mm H hF.2.2.2

lemma featA_9_7_2 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 9) (c 7) (θ 9 + 2 * (π / 2)) (θ 7)) :
    ∀ id ∈ (featRows.getD 11 []).getD 1 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 11 []).getD 1 [] = [46, 47] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_9_7_2_pp H hF.1
  · exact row_9_7_2_pm H hF.2.1

lemma pair_11 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 7) (θ 7) 1) (sqInt (c 9) (θ 9) 1)) :
    ∃ t < (featRows.getD 11 []).length, ∀ id ∈ (featRows.getD 11 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact ⟨0, by decide, featA_7_9_0 H h4⟩
    · exact absurd h4 (featU_7_9_1 H)
    · exact absurd h4 (featU_7_9_2 H)
    · exact absurd h4 (featU_7_9_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_9_7_0 H)
    · exact absurd h4 (featU_9_7_1 H)
    · exact ⟨1, by decide, featA_9_7_2 H h4⟩
    · exact absurd h4 (featU_9_7_3 H)

lemma featA_8_9_3 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 8) (c 9) (θ 8 + 3 * (π / 2)) (θ 9)) :
    ∀ id ∈ (featRows.getD 12 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 12 []).getD 0 [] = [48, 49] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_8_9_3_pp H hF.1
  · exact row_8_9_3_mp H hF.2.2.1

lemma featA_9_8_1 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 9) (c 8) (θ 9 + 1 * (π / 2)) (θ 8)) :
    ∀ id ∈ (featRows.getD 12 []).getD 1 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 12 []).getD 1 [] = [50, 51] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_9_8_1_pm H hF.2.1
  · exact row_9_8_1_mm H hF.2.2.2

lemma pair_12 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 8) (θ 8) 1) (sqInt (c 9) (θ 9) 1)) :
    ∃ t < (featRows.getD 12 []).length, ∀ id ∈ (featRows.getD 12 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_8_9_0 H)
    · exact absurd h4 (featU_8_9_1 H)
    · exact absurd h4 (featU_8_9_2 H)
    · exact ⟨0, by decide, featA_8_9_3 H h4⟩
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_9_8_0 H)
    · exact ⟨1, by decide, featA_9_8_1 H h4⟩
    · exact absurd h4 (featU_9_8_2 H)
    · exact absurd h4 (featU_9_8_3 H)

lemma featA_9_10_0 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 9) (c 10) (θ 9 + 0 * (π / 2)) (θ 10)) :
    ∀ id ∈ (featRows.getD 13 []).getD 0 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 13 []).getD 0 [] = [52, 53] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_9_10_0_mp H hF.2.2.1
  · exact row_9_10_0_mm H hF.2.2.2

lemma featA_10_9_2 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hF : Feat (c 10) (c 9) (θ 10 + 2 * (π / 2)) (θ 9)) :
    ∀ id ∈ (featRows.getD 13 []).getD 1 [], RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  rw [show (featRows.getD 13 []).getD 1 [] = [54, 55] from rfl] at hid
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl
  · exact row_10_9_2_pp H hF.1
  · exact row_10_9_2_pm H hF.2.1

lemma pair_13 {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : Disjoint (sqInt (c 9) (θ 9) 1) (sqInt (c 10) (θ 10) 1)) :
    ∃ t < (featRows.getD 13 []).length, ∀ id ∈ (featRows.getD 13 []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  obtain ⟨k, hk | hk⟩ := sat_necessary hd
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact ⟨0, by decide, featA_9_10_0 H h4⟩
    · exact absurd h4 (featU_9_10_1 H)
    · exact absurd h4 (featU_9_10_2 H)
    · exact absurd h4 (featU_9_10_3 H)
  · have h4 := feat_mod4 k hk
    rcases mod4_cases k with e | e | e | e <;> rw [e] at h4
    · exact absurd h4 (featU_10_9_0 H)
    · exact absurd h4 (featU_10_9_1 H)
    · exact ⟨1, by decide, featA_10_9_2 H h4⟩
    · exact absurd h4 (featU_10_9_3 H)

theorem pairs_all {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hd : ∀ i j : Fin 11, i ≠ j → Disjoint (sqInt (c i) (θ i) 1) (sqInt (c j) (θ j) 1)) :
    ∀ q < featRows.length, ∃ t < (featRows.getD q []).length, ∀ id ∈ (featRows.getD q []).getD t [],
      RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro q hq
  have hq' : q < 14 := hq
  interval_cases q
  · exact pair_0 H (hd 0 6 (by decide))
  · exact pair_1 H (hd 1 9 (by decide))
  · exact pair_2 H (hd 2 8 (by decide))
  · exact pair_3 H (hd 2 10 (by decide))
  · exact pair_4 H (hd 3 4 (by decide))
  · exact pair_5 H (hd 3 5 (by decide))
  · exact pair_6 H (hd 4 5 (by decide))
  · exact pair_7 H (hd 4 8 (by decide))
  · exact pair_8 H (hd 5 6 (by decide))
  · exact pair_9 H (hd 6 7 (by decide))
  · exact pair_10 H (hd 6 8 (by decide))
  · exact pair_11 H (hd 7 9 (by decide))
  · exact pair_12 H (hd 8 9 (by decide))
  · exact pair_13 H (hd 9 10 (by decide))

theorem walls_all {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : ∀ i : Fin 11, Adm T (c i) (θ i)) :
    ∀ id ∈ wallIds, RowOK (rowsS.getD id []) (kts.getD id 0) (hvOf c θ) τ := by
  intro id hid
  simp only [wallIds, List.mem_cons, List.not_mem_nil, or_false] at hid
  rcases hid with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact wrow_0_xlo_pp H (hA 0)
  · exact wrow_0_xlo_pm H (hA 0)
  · exact wrow_0_ylo_pp H (hA 0)
  · exact wrow_0_ylo_pm H (hA 0)
  · exact wrow_1_xhi_pp H (hA 1)
  · exact wrow_1_xhi_pm H (hA 1)
  · exact wrow_1_ylo_pp H (hA 1)
  · exact wrow_1_ylo_pm H (hA 1)
  · exact wrow_2_yhi_pp H (hA 2)
  · exact wrow_2_yhi_pm H (hA 2)
  · exact wrow_3_xlo_pp H (hA 3)
  · exact wrow_3_xlo_pm H (hA 3)
  · exact wrow_3_yhi_pp H (hA 3)
  · exact wrow_3_yhi_pm H (hA 3)
  · exact wrow_4_yhi_pp H (hA 4)
  · exact wrow_4_yhi_pm H (hA 4)
  · exact wrow_5_xlo_pp H (hA 5)
  · exact wrow_5_xlo_pm H (hA 5)
  · exact wrow_7_ylo_pp H (hA 7)
  · exact wrow_10_xhi_pp H (hA 10)

end SquarePacking.S11Opt.Split.U4
