import Sqpack.S11Opt.Split.U4.Data

/-! Generated by `scripts/u4/gen_lean.py`.  Do not edit by hand. -/

set_option maxHeartbeats 4000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.style.longLine false

open Real SquarePacking.S11Opt

namespace SquarePacking.S11Opt.Split.U4

lemma wrow_0_xlo_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 0) (θ 0)) :
    RowOK (rowsS.getD 0 []) (kts.getD 0 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).1
  have b2 := H.bd (k := 2) (by norm_num) (r := (5670363 / 2500000000 : ℝ)) (by rw [show rI.getD 2 0 = 22681452 from rfl]; norm_num [DR])
  have v0 : hvOf c θ 0 = (c 0).1 - (ctr 0).1 := hv_x c θ 0
  have v2 : hvOf c θ 2 = θ 0 - ang 0 := hv_t c θ 0
  have hx : |θ 0 - ang 0| ≤ τ * (5670363 / 2500000000 : ℝ) := by rw [← v2]; exact b2
  have hc : cos (ang 0) = 1 := by rw [ang_0]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 0) = 0 := by rw [ang_0]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 0).1) (cq' := (c 0).1) (σ := 1) (κ := 0) (θ := ang 0)
    (x := θ 0 - ang 0) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 0 + (θ 0 - ang 0) = θ 0 by ring] at key
  have hbase : wgap (ctr 0).1 1 0 (ang 0) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_0]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (80443314471220346174049 / 62500000000000000000000000000 : ℝ) ≤ τ * (128709303153953 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_0, kt_0]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v0, v2]
  norm_num [DA, DK]
  linarith

lemma wrow_0_xlo_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 0) (θ 0)) :
    RowOK (rowsS.getD 1 []) (kts.getD 1 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).1
  have b2 := H.bd (k := 2) (by norm_num) (r := (5670363 / 2500000000 : ℝ)) (by rw [show rI.getD 2 0 = 22681452 from rfl]; norm_num [DR])
  have v0 : hvOf c θ 0 = (c 0).1 - (ctr 0).1 := hv_x c θ 0
  have v2 : hvOf c θ 2 = θ 0 - ang 0 := hv_t c θ 0
  have hx : |θ 0 - ang 0| ≤ τ * (5670363 / 2500000000 : ℝ) := by rw [← v2]; exact b2
  have hc : cos (ang 0) = 1 := by rw [ang_0]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 0) = 0 := by rw [ang_0]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 0).1) (cq' := (c 0).1) (σ := 1) (κ := 0) (θ := ang 0)
    (x := θ 0 - ang 0) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 0 + (θ 0 - ang 0) = θ 0 by ring] at key
  have hbase : wgap (ctr 0).1 1 0 (ang 0) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_0]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (80443314471220346174049 / 62500000000000000000000000000 : ℝ) ≤ τ * (128709303153953 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_1, kt_1]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v0, v2]
  norm_num [DA, DK]
  linarith

lemma wrow_0_ylo_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 0) (θ 0)) :
    RowOK (rowsS.getD 2 []) (kts.getD 2 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).2.2.1
  have b2 := H.bd (k := 2) (by norm_num) (r := (5670363 / 2500000000 : ℝ)) (by rw [show rI.getD 2 0 = 22681452 from rfl]; norm_num [DR])
  have v1 : hvOf c θ 1 = (c 0).2 - (ctr 0).2 := hv_y c θ 0
  have v2 : hvOf c θ 2 = θ 0 - ang 0 := hv_t c θ 0
  have hx : |θ 0 - ang 0| ≤ τ * (5670363 / 2500000000 : ℝ) := by rw [← v2]; exact b2
  have hc : cos (ang 0) = 1 := by rw [ang_0]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 0) = 0 := by rw [ang_0]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 0).2) (cq' := (c 0).2) (σ := 1) (κ := 0) (θ := ang 0)
    (x := θ 0 - ang 0) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 0 + (θ 0 - ang 0) = θ 0 by ring] at key
  have hbase : wgap (ctr 0).2 1 0 (ang 0) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_0]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (80443314471220346174049 / 62500000000000000000000000000 : ℝ) ≤ τ * (128709303153953 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_2, kt_2]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v1, v2]
  norm_num [DA, DK]
  linarith

lemma wrow_0_ylo_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 0) (θ 0)) :
    RowOK (rowsS.getD 3 []) (kts.getD 3 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).2.2.1
  have b2 := H.bd (k := 2) (by norm_num) (r := (5670363 / 2500000000 : ℝ)) (by rw [show rI.getD 2 0 = 22681452 from rfl]; norm_num [DR])
  have v1 : hvOf c θ 1 = (c 0).2 - (ctr 0).2 := hv_y c θ 0
  have v2 : hvOf c θ 2 = θ 0 - ang 0 := hv_t c θ 0
  have hx : |θ 0 - ang 0| ≤ τ * (5670363 / 2500000000 : ℝ) := by rw [← v2]; exact b2
  have hc : cos (ang 0) = 1 := by rw [ang_0]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 0) = 0 := by rw [ang_0]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 0).2) (cq' := (c 0).2) (σ := 1) (κ := 0) (θ := ang 0)
    (x := θ 0 - ang 0) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 0 + (θ 0 - ang 0) = θ 0 by ring] at key
  have hbase : wgap (ctr 0).2 1 0 (ang 0) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_0]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (80443314471220346174049 / 62500000000000000000000000000 : ℝ) ≤ τ * (128709303153953 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_3, kt_3]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v1, v2]
  norm_num [DA, DK]
  linarith

lemma wrow_1_xhi_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 1) (θ 1)) :
    RowOK (rowsS.getD 4 []) (kts.getD 4 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).2.1
  have b5 := H.bd (k := 5) (by norm_num) (r := (1764113 / 1000000000 : ℝ)) (by rw [show rI.getD 5 0 = 17641130 from rfl]; norm_num [DR])
  have v3 : hvOf c θ 3 = (c 1).1 - (ctr 1).1 := hv_x c θ 1
  have v5 : hvOf c θ 5 = θ 1 - ang 1 := hv_t c θ 1
  have hx : |θ 1 - ang 1| ≤ τ * (1764113 / 1000000000 : ℝ) := by rw [← v5]; exact b5
  have hc : cos (ang 1) = 1 := by rw [ang_1]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 1) = 0 := by rw [ang_1]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 1).1) (cq' := (c 1).1) (σ := (-1)) (κ := T) (θ := ang 1)
    (x := θ 1 - ang 1) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 1 + (θ 1 - ang 1) = θ 1 by ring] at key
  have hbase : wgap (ctr 1).1 (-1) T (ang 1) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_1]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (9341774116983518990897 / 12000000000000000000000000000 : ℝ) ≤ τ * (77848117641530 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_4, kt_4]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v3, v5]
  norm_num [DA, DK]
  linarith

lemma wrow_1_xhi_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 1) (θ 1)) :
    RowOK (rowsS.getD 5 []) (kts.getD 5 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).2.1
  have b5 := H.bd (k := 5) (by norm_num) (r := (1764113 / 1000000000 : ℝ)) (by rw [show rI.getD 5 0 = 17641130 from rfl]; norm_num [DR])
  have v3 : hvOf c θ 3 = (c 1).1 - (ctr 1).1 := hv_x c θ 1
  have v5 : hvOf c θ 5 = θ 1 - ang 1 := hv_t c θ 1
  have hx : |θ 1 - ang 1| ≤ τ * (1764113 / 1000000000 : ℝ) := by rw [← v5]; exact b5
  have hc : cos (ang 1) = 1 := by rw [ang_1]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 1) = 0 := by rw [ang_1]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 1).1) (cq' := (c 1).1) (σ := (-1)) (κ := T) (θ := ang 1)
    (x := θ 1 - ang 1) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 1 + (θ 1 - ang 1) = θ 1 by ring] at key
  have hbase : wgap (ctr 1).1 (-1) T (ang 1) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_1]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (9341774116983518990897 / 12000000000000000000000000000 : ℝ) ≤ τ * (77848117641530 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_5, kt_5]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v3, v5]
  norm_num [DA, DK]
  linarith

lemma wrow_1_ylo_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 1) (θ 1)) :
    RowOK (rowsS.getD 6 []) (kts.getD 6 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).2.2.1
  have b5 := H.bd (k := 5) (by norm_num) (r := (1764113 / 1000000000 : ℝ)) (by rw [show rI.getD 5 0 = 17641130 from rfl]; norm_num [DR])
  have v4 : hvOf c θ 4 = (c 1).2 - (ctr 1).2 := hv_y c θ 1
  have v5 : hvOf c θ 5 = θ 1 - ang 1 := hv_t c θ 1
  have hx : |θ 1 - ang 1| ≤ τ * (1764113 / 1000000000 : ℝ) := by rw [← v5]; exact b5
  have hc : cos (ang 1) = 1 := by rw [ang_1]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 1) = 0 := by rw [ang_1]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 1).2) (cq' := (c 1).2) (σ := 1) (κ := 0) (θ := ang 1)
    (x := θ 1 - ang 1) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 1 + (θ 1 - ang 1) = θ 1 by ring] at key
  have hbase : wgap (ctr 1).2 1 0 (ang 1) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_1]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (9341774116983518990897 / 12000000000000000000000000000 : ℝ) ≤ τ * (77848117641530 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_6, kt_6]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v4, v5]
  norm_num [DA, DK]
  linarith

lemma wrow_1_ylo_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 1) (θ 1)) :
    RowOK (rowsS.getD 7 []) (kts.getD 7 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).2.2.1
  have b5 := H.bd (k := 5) (by norm_num) (r := (1764113 / 1000000000 : ℝ)) (by rw [show rI.getD 5 0 = 17641130 from rfl]; norm_num [DR])
  have v4 : hvOf c θ 4 = (c 1).2 - (ctr 1).2 := hv_y c θ 1
  have v5 : hvOf c θ 5 = θ 1 - ang 1 := hv_t c θ 1
  have hx : |θ 1 - ang 1| ≤ τ * (1764113 / 1000000000 : ℝ) := by rw [← v5]; exact b5
  have hc : cos (ang 1) = 1 := by rw [ang_1]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 1) = 0 := by rw [ang_1]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 1).2) (cq' := (c 1).2) (σ := 1) (κ := 0) (θ := ang 1)
    (x := θ 1 - ang 1) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 1 + (θ 1 - ang 1) = θ 1 by ring] at key
  have hbase : wgap (ctr 1).2 1 0 (ang 1) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_1]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (9341774116983518990897 / 12000000000000000000000000000 : ℝ) ≤ τ * (77848117641530 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_7, kt_7]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v4, v5]
  norm_num [DA, DK]
  linarith

lemma wrow_2_yhi_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 2) (θ 2)) :
    RowOK (rowsS.getD 8 []) (kts.getD 8 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).2.2.2
  have b8 := H.bd (k := 8) (by norm_num) (r := (5670363 / 2500000000 : ℝ)) (by rw [show rI.getD 8 0 = 22681452 from rfl]; norm_num [DR])
  have v7 : hvOf c θ 7 = (c 2).2 - (ctr 2).2 := hv_y c θ 2
  have v8 : hvOf c θ 8 = θ 2 - ang 2 := hv_t c θ 2
  have hx : |θ 2 - ang 2| ≤ τ * (5670363 / 2500000000 : ℝ) := by rw [← v8]; exact b8
  have hc : cos (ang 2) = 1 := by rw [ang_2]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 2) = 0 := by rw [ang_2]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 2).2) (cq' := (c 2).2) (σ := (-1)) (κ := T) (θ := ang 2)
    (x := θ 2 - ang 2) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 2 + (θ 2 - ang 2) = θ 2 by ring] at key
  have hbase : wgap (ctr 2).2 (-1) T (ang 2) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_2]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (80443314471220346174049 / 62500000000000000000000000000 : ℝ) ≤ τ * (128709303153953 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_8, kt_8]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v7, v8]
  norm_num [DA, DK]
  linarith

lemma wrow_2_yhi_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 2) (θ 2)) :
    RowOK (rowsS.getD 9 []) (kts.getD 9 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).2.2.2
  have b8 := H.bd (k := 8) (by norm_num) (r := (5670363 / 2500000000 : ℝ)) (by rw [show rI.getD 8 0 = 22681452 from rfl]; norm_num [DR])
  have v7 : hvOf c θ 7 = (c 2).2 - (ctr 2).2 := hv_y c θ 2
  have v8 : hvOf c θ 8 = θ 2 - ang 2 := hv_t c θ 2
  have hx : |θ 2 - ang 2| ≤ τ * (5670363 / 2500000000 : ℝ) := by rw [← v8]; exact b8
  have hc : cos (ang 2) = 1 := by rw [ang_2]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 2) = 0 := by rw [ang_2]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 2).2) (cq' := (c 2).2) (σ := (-1)) (κ := T) (θ := ang 2)
    (x := θ 2 - ang 2) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 2 + (θ 2 - ang 2) = θ 2 by ring] at key
  have hbase : wgap (ctr 2).2 (-1) T (ang 2) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_2]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (80443314471220346174049 / 62500000000000000000000000000 : ℝ) ≤ τ * (128709303153953 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_9, kt_9]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v7, v8]
  norm_num [DA, DK]
  linarith

lemma wrow_3_xlo_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 3) (θ 3)) :
    RowOK (rowsS.getD 10 []) (kts.getD 10 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).1
  have b11 := H.bd (k := 11) (by norm_num) (r := (1890121 / 1250000000 : ℝ)) (by rw [show rI.getD 11 0 = 15120968 from rfl]; norm_num [DR])
  have v9 : hvOf c θ 9 = (c 3).1 - (ctr 3).1 := hv_x c θ 3
  have v11 : hvOf c θ 11 = θ 3 - ang 3 := hv_t c θ 3
  have hx : |θ 3 - ang 3| ≤ τ * (1890121 / 1250000000 : ℝ) := by rw [← v11]; exact b11
  have hc : cos (ang 3) = 1 := by rw [ang_3]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 3) = 0 := by rw [ang_3]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 3).1) (cq' := (c 3).1) (σ := 1) (κ := 0) (θ := ang 3)
    (x := θ 3 - ang 3) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 3 + (θ 3 - ang 3) = θ 3 by ring] at key
  have hbase : wgap (ctr 3).1 1 0 (ang 3) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_3]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (13403842795659066241561 / 23437500000000000000000000000 : ℝ) ≤ τ * (57189729261479 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_10, kt_10]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v9, v11]
  norm_num [DA, DK]
  linarith

lemma wrow_3_xlo_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 3) (θ 3)) :
    RowOK (rowsS.getD 11 []) (kts.getD 11 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).1
  have b11 := H.bd (k := 11) (by norm_num) (r := (1890121 / 1250000000 : ℝ)) (by rw [show rI.getD 11 0 = 15120968 from rfl]; norm_num [DR])
  have v9 : hvOf c θ 9 = (c 3).1 - (ctr 3).1 := hv_x c θ 3
  have v11 : hvOf c θ 11 = θ 3 - ang 3 := hv_t c θ 3
  have hx : |θ 3 - ang 3| ≤ τ * (1890121 / 1250000000 : ℝ) := by rw [← v11]; exact b11
  have hc : cos (ang 3) = 1 := by rw [ang_3]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 3) = 0 := by rw [ang_3]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 3).1) (cq' := (c 3).1) (σ := 1) (κ := 0) (θ := ang 3)
    (x := θ 3 - ang 3) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 3 + (θ 3 - ang 3) = θ 3 by ring] at key
  have hbase : wgap (ctr 3).1 1 0 (ang 3) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_3]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (13403842795659066241561 / 23437500000000000000000000000 : ℝ) ≤ τ * (57189729261479 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_11, kt_11]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v9, v11]
  norm_num [DA, DK]
  linarith

lemma wrow_3_yhi_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 3) (θ 3)) :
    RowOK (rowsS.getD 12 []) (kts.getD 12 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).2.2.2
  have b11 := H.bd (k := 11) (by norm_num) (r := (1890121 / 1250000000 : ℝ)) (by rw [show rI.getD 11 0 = 15120968 from rfl]; norm_num [DR])
  have v10 : hvOf c θ 10 = (c 3).2 - (ctr 3).2 := hv_y c θ 3
  have v11 : hvOf c θ 11 = θ 3 - ang 3 := hv_t c θ 3
  have hx : |θ 3 - ang 3| ≤ τ * (1890121 / 1250000000 : ℝ) := by rw [← v11]; exact b11
  have hc : cos (ang 3) = 1 := by rw [ang_3]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 3) = 0 := by rw [ang_3]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 3).2) (cq' := (c 3).2) (σ := (-1)) (κ := T) (θ := ang 3)
    (x := θ 3 - ang 3) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 3 + (θ 3 - ang 3) = θ 3 by ring] at key
  have hbase : wgap (ctr 3).2 (-1) T (ang 3) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_3]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (13403842795659066241561 / 23437500000000000000000000000 : ℝ) ≤ τ * (57189729261479 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_12, kt_12]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v10, v11]
  norm_num [DA, DK]
  linarith

lemma wrow_3_yhi_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 3) (θ 3)) :
    RowOK (rowsS.getD 13 []) (kts.getD 13 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).2.2.2
  have b11 := H.bd (k := 11) (by norm_num) (r := (1890121 / 1250000000 : ℝ)) (by rw [show rI.getD 11 0 = 15120968 from rfl]; norm_num [DR])
  have v10 : hvOf c θ 10 = (c 3).2 - (ctr 3).2 := hv_y c θ 3
  have v11 : hvOf c θ 11 = θ 3 - ang 3 := hv_t c θ 3
  have hx : |θ 3 - ang 3| ≤ τ * (1890121 / 1250000000 : ℝ) := by rw [← v11]; exact b11
  have hc : cos (ang 3) = 1 := by rw [ang_3]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 3) = 0 := by rw [ang_3]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 3).2) (cq' := (c 3).2) (σ := (-1)) (κ := T) (θ := ang 3)
    (x := θ 3 - ang 3) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 3 + (θ 3 - ang 3) = θ 3 by ring] at key
  have hbase : wgap (ctr 3).2 (-1) T (ang 3) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_3]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (13403842795659066241561 / 23437500000000000000000000000 : ℝ) ≤ τ * (57189729261479 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_13, kt_13]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v10, v11]
  norm_num [DA, DK]
  linarith

lemma wrow_4_yhi_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 4) (θ 4)) :
    RowOK (rowsS.getD 14 []) (kts.getD 14 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).2.2.2
  have b14 := H.bd (k := 14) (by norm_num) (r := (20161291 / 10000000000 : ℝ)) (by rw [show rI.getD 14 0 = 20161291 from rfl]; norm_num [DR])
  have v13 : hvOf c θ 13 = (c 4).2 - (ctr 4).2 := hv_y c θ 4
  have v14 : hvOf c θ 14 = θ 4 - ang 4 := hv_t c θ 4
  have hx : |θ 4 - ang 4| ≤ τ * (20161291 / 10000000000 : ℝ) := by rw [← v14]; exact b14
  have hc : cos (ang 4) = 1 := by rw [ang_4]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 4) = 0 := by rw [ang_4]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 4).2) (cq' := (c 4).2) (σ := (-1)) (κ := T) (θ := ang 4)
    (x := θ 4 - ang 4) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 4 + (θ 4 - ang 4) = θ 4 by ring] at key
  have hbase : wgap (ctr 4).2 (-1) T (ang 4) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_4]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (12202524757883581818565171 / 12000000000000000000000000000000 : ℝ) ≤ τ * (101687706315697 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_14, kt_14]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v13, v14]
  norm_num [DA, DK]
  linarith

lemma wrow_4_yhi_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 4) (θ 4)) :
    RowOK (rowsS.getD 15 []) (kts.getD 15 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).2.2.2
  have b14 := H.bd (k := 14) (by norm_num) (r := (20161291 / 10000000000 : ℝ)) (by rw [show rI.getD 14 0 = 20161291 from rfl]; norm_num [DR])
  have v13 : hvOf c θ 13 = (c 4).2 - (ctr 4).2 := hv_y c θ 4
  have v14 : hvOf c θ 14 = θ 4 - ang 4 := hv_t c θ 4
  have hx : |θ 4 - ang 4| ≤ τ * (20161291 / 10000000000 : ℝ) := by rw [← v14]; exact b14
  have hc : cos (ang 4) = 1 := by rw [ang_4]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 4) = 0 := by rw [ang_4]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 4).2) (cq' := (c 4).2) (σ := (-1)) (κ := T) (θ := ang 4)
    (x := θ 4 - ang 4) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 4 + (θ 4 - ang 4) = θ 4 by ring] at key
  have hbase : wgap (ctr 4).2 (-1) T (ang 4) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_4]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (12202524757883581818565171 / 12000000000000000000000000000000 : ℝ) ≤ τ * (101687706315697 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_15, kt_15]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v13, v14]
  norm_num [DA, DK]
  linarith

lemma wrow_5_xlo_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 5) (θ 5)) :
    RowOK (rowsS.getD 16 []) (kts.getD 16 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).1
  have b17 := H.bd (k := 17) (by norm_num) (r := (1890121 / 1250000000 : ℝ)) (by rw [show rI.getD 17 0 = 15120968 from rfl]; norm_num [DR])
  have v15 : hvOf c θ 15 = (c 5).1 - (ctr 5).1 := hv_x c θ 5
  have v17 : hvOf c θ 17 = θ 5 - ang 5 := hv_t c θ 5
  have hx : |θ 5 - ang 5| ≤ τ * (1890121 / 1250000000 : ℝ) := by rw [← v17]; exact b17
  have hc : cos (ang 5) = 1 := by rw [ang_5]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 5) = 0 := by rw [ang_5]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 5).1) (cq' := (c 5).1) (σ := 1) (κ := 0) (θ := ang 5)
    (x := θ 5 - ang 5) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 5 + (θ 5 - ang 5) = θ 5 by ring] at key
  have hbase : wgap (ctr 5).1 1 0 (ang 5) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_5]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (13403842795659066241561 / 23437500000000000000000000000 : ℝ) ≤ τ * (57189729261479 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_16, kt_16]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v15, v17]
  norm_num [DA, DK]
  linarith

lemma wrow_5_xlo_pm {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 5) (θ 5)) :
    RowOK (rowsS.getD 17 []) (kts.getD 17 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (by norm_num) (by norm_num)).1
  have b17 := H.bd (k := 17) (by norm_num) (r := (1890121 / 1250000000 : ℝ)) (by rw [show rI.getD 17 0 = 15120968 from rfl]; norm_num [DR])
  have v15 : hvOf c θ 15 = (c 5).1 - (ctr 5).1 := hv_x c θ 5
  have v17 : hvOf c θ 17 = θ 5 - ang 5 := hv_t c θ 5
  have hx : |θ 5 - ang 5| ≤ τ * (1890121 / 1250000000 : ℝ) := by rw [← v17]; exact b17
  have hc : cos (ang 5) = 1 := by rw [ang_5]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 5) = 0 := by rw [ang_5]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 5).1) (cq' := (c 5).1) (σ := 1) (κ := 0) (θ := ang 5)
    (x := θ 5 - ang 5) (s1 := (1 : ℝ)) (s2 := (-1 : ℝ)) (W := (1 / 2 : ℝ))
    (eW := (0 : ℝ)) (bF := (1 : ℝ)) (bF' := (1 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 5 + (θ 5 - ang 5) = θ 5 by ring] at key
  have hbase : wgap (ctr 5).1 1 0 (ang 5) (1 : ℝ) (-1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_5]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (13403842795659066241561 / 23437500000000000000000000000 : ℝ) ≤ τ * (57189729261479 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_17, kt_17]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v15, v17]
  norm_num [DA, DK]
  linarith

lemma wrow_7_ylo_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 7) (θ 7)) :
    RowOK (rowsS.getD 18 []) (kts.getD 18 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).2.2.1
  have b23 := H.bd (k := 23) (by norm_num) (r := (8824483 / 2500000000 : ℝ)) (by rw [show rI.getD 23 0 = 35297932 from rfl]; norm_num [DR])
  have v22 : hvOf c θ 22 = (c 7).2 - (ctr 7).2 := hv_y c θ 7
  have v23 : hvOf c θ 23 = θ 7 - ang 7 := hv_t c θ 7
  have hx : |θ 7 - ang 7| ≤ τ * (8824483 / 2500000000 : ℝ) := by rw [← v23]; exact b23
  have hc : cos (ang 7) = cA := by rw [ang_7]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 7) = sA := by rw [ang_7]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 7).2) (cq' := (c 7).2) (σ := 1) (κ := 0) (θ := ang 7)
    (x := θ 7 - ang 7) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-185597824296021043 / 3125000000000000000 : ℝ))
    (eW := (1 / 1000000000000000000000 : ℝ)) (bF := (1100950265409 / 781250000000 : ℝ)) (bF' := (59391303774727 / 500000000000000 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 7 + (θ 7 - ang 7) = θ 7 by ring] at key
  have hbase : wgap (ctr 7).2 1 0 (ang 7) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_7]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (411557526656220621465589202859043286749 / 93750000000000000000000000000000000000000000 : ℝ) ≤ τ * (438994695099969 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_18, kt_18]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v22, v23]
  norm_num [DA, DK]
  linarith

lemma wrow_10_xhi_pp {c : Fin 11 → ℝ × ℝ} {θ : Fin 11 → ℝ} {τ : ℝ} (H : Pert c θ τ)
    (hA : Adm T (c 10) (θ 10)) :
    RowOK (rowsS.getD 19 []) (kts.getD 19 0) (hvOf c θ) τ := by
  have hF := (wgap_nonneg hA (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (by norm_num) (by norm_num)).2.1
  have b32 := H.bd (k := 32) (by norm_num) (r := (67647473 / 10000000000 : ℝ)) (by rw [show rI.getD 32 0 = 67647473 from rfl]; norm_num [DR])
  have v30 : hvOf c θ 30 = (c 10).1 - (ctr 10).1 := hv_x c θ 10
  have v32 : hvOf c θ 32 = θ 10 - ang 10 := hv_t c θ 10
  have hx : |θ 10 - ang 10| ≤ τ * (67647473 / 10000000000 : ℝ) := by rw [← v32]; exact b32
  have hc : cos (ang 10) = cA := by rw [ang_10]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have hs : sin (ang 10) = sA := by rw [ang_10]; simp [cos_zero, sin_zero, cos_a, sin_a, sub_zero, zero_sub, sub_self, cos_neg, sin_neg, neg_neg]
  have key := wgap_approx (cq := (ctr 10).1) (cq' := (c 10).1) (σ := (-1)) (κ := T) (θ := ang 10)
    (x := θ 10 - ang 10) (s1 := (1 : ℝ)) (s2 := (1 : ℝ)) (W := (-185597824296021043 / 3125000000000000000 : ℝ))
    (eW := (1 / 1000000000000000000000 : ℝ)) (bF := (1100950265409 / 781250000000 : ℝ)) (bF' := (59391303774727 / 500000000000000 : ℝ))
    H.τ0 H.τ1 (by norm_num) hx
    (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2]) (by rw [hc, hs]; rw [abs_le]; constructor <;> linarith [hcAe.1, hcAe.2, hsAe.1, hsAe.2])
  rw [show ang 10 + (θ 10 - ang 10) = θ 10 by ring] at key
  have hbase : wgap (ctr 10).1 (-1) T (ang 10) (1 : ℝ) (1 : ℝ) = 0 := by
    unfold wgap; rw [hc, hs, ctr_10]; simp only [T_eq, cA, sA, TA, x0, y0, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8, x9, y9, x10, y10, pe, List.foldr, peQ_cons, peQ_nil]
    linear_combination 0 * P_u₀'
  rw [hbase] at key
  have hK : τ * (96750812786072383166027250052033063275959 / 6000000000000000000000000000000000000000000000 : ℝ) ≤ τ * (1612513546434540 / 100000000000000000000 : ℝ) :=
    mul_le_mul_of_nonneg_left (by norm_num) H.τ0
  have hk := (abs_le.mp key).2
  rw [row_19, kt_19]
  unfold RowOK spVal
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, v30, v32]
  norm_num [DA, DK]
  linarith

end SquarePacking.S11Opt.Split.U4
