"""Branching version of the generator: when the induction stops growing, split the centre of one
owner by an axis-parallel grid half-plane and solve both halves (Lean: `U2P/Branch.lean`,
`split_excl`).  Usage: python3 branch.py CASE OUTDIR [PREFIX] [MAXDEPTH]"""
import os
import sys
import time
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from gen_u2p import (Step, Owned, CAN, M, R, Q, BASE, FUEL, CHUNK, area, encode, numeral, nleaves, pts)


def run_rounds(J, cs, cur, steps, node, max_rounds, log):
    last = {}
    t0 = time.time()
    for rnd in range(max_rounds):
        progress = False
        for o in J:
            others = [cur[o2] for o2 in J if o2 != o and o2 in cur]
            conds = [h for (oo, h) in cs if oo == o]
            st = Step(len(steps), o, others, conds=conds).run()
            st.node, st.cs = node, list(cs)
            if not st.alive:
                steps.append((st, None))
                log(f'[{node}] rnd {rnd} owner {o}: TERMINAL leaves {st.nleaves} ({time.time() - t0:.0f}s)')
                return ('term', node, list(cs), st.sid), last
            tg = st.targets()
            st.root = None                   # keep only the encoded tree (memory)
            new = None
            if len(tg) >= 3 and area(tg) > (area(cur[o].verts) if o in cur else 0) + 1e-6:
                new = Owned(st.sid, o, tg)
                cur[o] = new
                progress = True
            steps.append((st, new))
            last[o] = st
            log(f'[{node}] rnd {rnd} owner {o}: leaves {st.nleaves} alive {len(st.alive)} '
                f'area {area(cur[o].verts) if o in cur else 0:.4f} ({time.time() - t0:.0f}s)')
        if not progress:
            return None, last
    return None, last


def split_candidates(last):
    out = []
    for o, st in last.items():
        cxs = sorted((b[1] + b[2]) // 2 for b in st.alive)
        cys = sorted((b[3] + b[4]) // 2 for b in st.alive)
        if not cxs:
            continue
        wx, wy = cxs[-1] - cxs[0], cys[-1] - cys[0]
        if wx >= wy:
            out.append((wx * wy, o, (1, 0, cxs[len(cxs) // 2])))
        else:
            out.append((wx * wy, o, (0, 1, cys[len(cys) // 2])))
    out.sort(reverse=True)
    return out


def solve(J, cs, cur, steps, depth, maxd, log, node='r', ncand=2):
    res, last = run_rounds(J, cs, cur, steps, node, 30, log)
    if res:
        return res
    if depth >= maxd:
        return None
    cands = [(o, h) for _, o, h in split_candidates(last)[:ncand]]
    forced = os.environ.get('U2P_FIRST_SPLIT')     # "owner,A,B,C": the first split of the root
    if forced and node == 'r':
        o, a, b, c = (int(x) for x in forced.split(','))
        cands = [(o, (a, b, c))] + cands
    for o, h in cands:
        nh = (-h[0], -h[1], -h[2])
        log(f'[{node}] split owner {o} by {h}')
        L = solve(J, [(o, h)] + cs, dict(cur), steps, depth + 1, maxd, log, node + 'L', ncand)
        if not L:
            continue
        Rr = solve(J, [(o, nh)] + cs, dict(cur), steps, depth + 1, maxd, log, node + 'R', ncand)
        if not Rr:
            continue
        return ('split', node, list(cs), o, h, L, Rr)
    return None


def terminals(t):
    return [t[3]] if t[0] == 'term' else terminals(t[5]) + terminals(t[6])


def nodes(t):
    return [t] if t[0] == 'term' else [t] + nodes(t[5]) + nodes(t[6])


def needed(steps, tree):
    need = set()
    stack = terminals(tree)
    while stack:
        s = stack.pop()
        if s in need:
            continue
        need.add(s)
        for (sid, ti) in steps[s][0].dead_used:
            stack.append(sid)
    return sorted(need)


def cs_lean(cs):
    return "[" + ", ".join(f"({o}, ({a}, {b}, {c}))" for o, (a, b, c) in cs) + "]"


def emit(ci, J, steps, tree, outdir, prefix="U2P"):
    ns = f"SquarePacking.S11Opt.Split.{prefix}.C{ci}"
    mod = f"Sqpack.S11Opt.Split.{prefix}.C{ci}"
    opn = "" if prefix == "U2P" else "open SquarePacking.S11Opt.Split.U2P\n"
    d = os.path.join(outdir, f"C{ci}")
    os.makedirs(d, exist_ok=True)
    keep = needed(steps, tree)
    ren = {s: n for n, s in enumerate(keep)}
    owned_of = {st.sid: new for st, new in steps}
    data = ["import Sqpack.S11Opt.Split.U2P.Branch\n",
            f"/-! Generated by `scripts/u2p/branch.py`: case {ci}, cells {list(J)}. -/\n",
            "set_option linter.style.longLine false\n", "set_option maxRecDepth 100000\n",
            f"namespace {ns}\n", "open FieldTree\n" + opn, f"def J : List ℕ := {list(J)}\n"]
    for t in nodes(tree):
        data.append(f"def cs_{t[1]} : List Cond := {cs_lean(t[2])}")
    data.append("")
    info = []
    for s in keep:
        st, new = steps[s]
        n = ren[s]
        keys = sorted(st.dead_used)
        opt_index = {}
        tl = []
        for i, key in enumerate(keys):
            sid, ti = key
            hO = owned_of[sid]
            a, b, c = hO.tris[ti]
            ws = sorted(st.dead_used[key])
            opt_index[key] = (i, {w: k for k, w in enumerate(ws)})
            tl.append(f"({hO.owner}, ({a[0]}, {a[1]}), ({b[0]}, {b[1]}), ({c[0]}, {c[1]}), {pts(ws)}, "
                      f"[{', '.join('[' + ', '.join(map(str, st.dead_used[key][w])) + ']' for w in ws)}])")
        data.append(f"/-- Step {n}: owner {st.o}, branch {st.node}. -/")
        data.append(f"def tris{n} : List Tri := [{', '.join(tl)}]")
        if new:
            data.append(f"def tgt{n} : List (ℕ × ℕ) := {pts(new.verts)}")
            data.append(f"def opts{n} : List (List (List (ℕ × ℕ))) := stepOpts tris{n} tgt{n}\n")
        else:
            data.append(f"def opts{n} : List (List (List (ℕ × ℕ))) := triOpts tris{n}\n")
        info.append((n, st, new, keys, opt_index, len(keys), len(new.verts) if new else 0))
    data.append(f"end {ns}\n")
    open(os.path.join(d, "Data.lean"), "w").write("\n".join(data))
    for n, st, new, keys, opt_index, T_index, ntg in info:
        hp = f"(hpsC {st.o} ++ condsOf cs_{st.node} {st.o})"
        lines = [f"import {mod}.Data\n", "set_option linter.style.longLine false\n",
                 f"namespace {ns}\n", "open FieldTree\n" + opn]
        cnt = [0]

        def chunks(t, box):
            x0, x1, y0, y1, u0, u1 = box
            stmt = f"CovF G.Q G.M G.R {hp} opts{n} {x0} {x1} {y0} {y1} {u0} {u1}"
            cnt[0] += 1
            nm = f"cov{n}_{cnt[0]}"
            if nleaves(t) <= CHUNK:
                dg = []
                encode(t, opt_index, T_index, ntg, dg)
                lines.append(f"theorem {nm} : {stmt} :=\n  soundDec G.Q G.M G.R {BASE} {FUEL} {numeral(dg)} "
                             f"G.Q_pos G.R_pos {hp} opts{n} (by decide +kernel)\n")
                return nm
            ax = t[0]
            if ax == 'X':
                m = (x0 + x1) // 2; b1, b2 = (x0, m, y0, y1, u0, u1), (m, x1, y0, y1, u0, u1)
            elif ax == 'Y':
                m = (y0 + y1) // 2; b1, b2 = (x0, x1, y0, m, u0, u1), (x0, x1, m, y1, u0, u1)
            else:
                m = (u0 + u1) // 2; b1, b2 = (x0, x1, y0, y1, u0, m), (x0, x1, y0, y1, m, u1)
            l = chunks(t[1], b1)
            r = chunks(t[2], b2)
            lines.append(f"theorem {nm} : {stmt} :=\n  CovF.split{ax} {m} {l} {r}\n")
            return nm
        root = chunks(st.tree, (0, M, 0, M, 0, R))
        lines.append(f"theorem cov{n} : CovF G.Q G.M G.R {hp} opts{n} 0 {M} 0 {M} 0 {R} := {root}\n")
        lines.append(f"end {ns}\n")
        open(os.path.join(d, f"S{n}.lean"), "w").write("\n".join(lines))
    L = [f"import {mod}.S{n}" for n, *_ in info]
    L += ["\nset_option linter.style.longLine false\nset_option maxRecDepth 100000\n", f"namespace {ns}\n", "open FieldTree\n" + opn,
          f"lemma hJ : J = maskAt {ci} := by decide +kernel\n"]

    def valid(n, st, keys):
        if not keys:
            return f"by intro t ht; simp [tris{n}] at ht"
        out = ["by", "    intro t ht",
               f"    simp only [tris{n}, List.mem_cons, List.not_mem_nil, or_false] at ht",
               "    rcases ht with " + " | ".join("rfl" for _ in keys)]
        for key in keys:
            m = ren[key[0]]
            fact = f"(own{m} _ (by decide)).mono (by decide)"
            out.append(f"    · exact ⟨by decide, by decide, {fact}, {fact}, {fact}, by decide +kernel⟩")
        return "\n".join(out)
    term_step = {}
    for n, st, new, keys, opt_index, T_index, ntg in info:
        if new:
            L.append(f"theorem own{n} : ∀ p ∈ tgt{n}, OwnedC Ux J cs_{st.node} {st.o} p :=\n"
                     f"  owned_all_of_trisC le_rfl (by norm_num [Ux]) (by decide) (by decide)\n"
                     f"    ({valid(n, st, keys)}) cov{n}\n")
        else:
            term_step[st.node] = (n, st, keys)
    for t in reversed(nodes(tree)):
        if t[0] == 'term':
            n, st, keys = term_step[t[1]]
            L.append(f"theorem excl_{t[1]} : Excl Ux J cs_{t[1]} :=\n"
                     f"  excluded_of_trisC le_rfl (by norm_num [Ux]) (by decide) (by decide)\n"
                     f"    ({valid(n, st, keys)}) cov{n}\n")
        else:
            _, node, cs, o, (a, b, c), Lt, Rt = t
            L.append(f"theorem excl_{node} : Excl Ux J cs_{node} :=\n"
                     f"  split_excl {o} ({a}) ({b}) ({c}) excl_{Lt[1]} excl_{Rt[1]}\n")
    L.append("theorem notIn : ¬ RealizesIn Ux J := not_in_of_excl excl_r\n")
    L.append(f"theorem excluded : CaseExcluded (maskAt {ci}) := by\n  rw [← hJ]; exact caseExcluded_of_not_in notIn\n")
    L.append(f"end {ns}\n")
    open(os.path.join(d, "Main.lean"), "w").write("\n".join(L))
    return len(keep), sum(nleaves(st.tree) for _, st, *_ in info)


def exclude_branch(ci, maxd=3, log=print):
    J = CAN[ci]
    steps = []
    tree = solve(J, [], {}, steps, 0, maxd, log)
    return J, steps, tree


if __name__ == '__main__':
    ci = int(sys.argv[1]); outdir = sys.argv[2]
    prefix = sys.argv[3] if len(sys.argv) > 3 else "U2P"
    maxd = int(sys.argv[4]) if len(sys.argv) > 4 else 3
    J, steps, tree = exclude_branch(ci, maxd, log=lambda s: print(s, flush=True))
    if tree is None:
        print('FAILED'); sys.exit(1)
    k, tot = emit(ci, J, steps, tree, outdir, prefix)
    print(f'case {ci}: {len(steps)} steps searched, {k} kept, {tot} leaves; tree {len(nodes(tree))} nodes')
