"""Write lean/Sqpack/S11Opt/Split/U2Prior.lean: `prior_excluded` from the 76 case theorems
`U2P.C<i>.excluded` (generated by gen_u2p.py / branch.py).  Usage: python3 make_prior.py OUT.lean"""
import re
import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, '..', '..', 'lean', 'Sqpack', 'S11Opt', 'Split', 'Interface.lean')).read()
prior = [int(x) for x in re.search(r'def priorIdx : List ℕ := \[(.*?)\]', src).group(1).split(',')]
assert len(prior) == 76
L = [f"import Sqpack.S11Opt.Split.U2P.C{i}.Main" for i in prior]
L += ["", "set_option linter.style.longLine false", "",
      "/-!",
      "# U2 — prior cases (76; PROOF.md §5)",
      "",
      "Owner: f1.  Each case `i` is excluded by `U2P.C<i>.excluded`, an owned-hull induction with box",
      "trees generated by `scripts/u2p/gen_u2p.py` (rules in `U2P/Rules.lean`, branches in",
      "`U2P/Branch.lean`).  The generated files are not in the repository; `scripts/u2p/MANIFEST_U2P.sha256`",
      "records their hashes.  Nothing of the author's prior certificates is used.",
      "-/",
      "",
      "namespace SquarePacking.S11Opt.Split",
      "",
      "/-- **U2 (prior).** -/",
      "theorem prior_excluded : ∀ i ∈ priorIdx, CaseExcluded (maskAt i) := by",
      "  intro i hi",
      "  simp only [priorIdx, List.mem_cons, List.not_mem_nil, or_false] at hi",
      "  rcases hi with " + " | ".join("rfl" for _ in prior)]
L += [f"  · exact U2P.C{i}.excluded" for i in prior]
L += ["", "end SquarePacking.S11Opt.Split", ""]
open(sys.argv[1], "w").write("\n".join(L))
