"""Write the unit theorem of a U2 family from the per-case theorems of the generator.

  python3 gen_agg.py generic  OUT.lean   # U2Generic.lean: generic_excluded over genericIdx (prefix U2G)
  python3 gen_agg.py returned OUT.lean   # U2Returned.lean: returned_excluded over returnedIdx (prefix U2R)

The case list is read from `Split/Interface.lean`; each case module
`Sqpack.S11Opt.Split.<PREFIX>.C<case>.Main` proves `<PREFIX>.C<case>.excluded`.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
IFACE = os.path.join(HERE, '../../lean/Sqpack/S11Opt/Split/Interface.lean')
FAM = {'generic': ('genericIdx', 'U2G', 'generic_excluded', 'U2Generic', '27 generic'),
       'returned': ('returnedIdx', 'U2R', 'returned_excluded', 'U2Returned', '173 returned')}


def cases(name):
    src = open(IFACE).read()
    m = re.search(r'def ' + name + r' : List ℕ := \[([^\]]*)\]', src)
    return [int(x) for x in m.group(1).split(',')]


def main(fam, out):
    idx, pfx, thm, unit, what = FAM[fam]
    cs = cases(idx)
    L = [f"import Sqpack.S11Opt.Split.{pfx}.C{c}.Main" for c in cs]
    L += ["", "/-!", f"# {unit} — the {what} cases (PROOF.md §5)", "",
          "Each case is excluded by the owned-hull induction (`U2Rules`, `U2P/Rules.lean`, `U2P/Branch.lean`)",
          f"with box trees written by `scripts/u2p/` (prefix `{pfx}`); this file collects the per-case",
          f"theorems `{pfx}.C<case>.excluded`.  Generated by `scripts/u2agg/gen_agg.py`.", "-/", "",
          "namespace SquarePacking.S11Opt.Split", "",
          f"/-- **U2 ({fam}).** -/",
          f"theorem {thm} : ∀ i ∈ {idx}, CaseExcluded (maskAt i) := by",
          "  intro i hi",
          f"  simp only [{idx}, List.mem_cons, List.not_mem_nil, or_false] at hi",
          "  rcases hi with " + " | ".join(["rfl"] * len(cs))]
    L += [f"  · exact {pfx}.C{c}.excluded" for c in cs]
    L += ["", "end SquarePacking.S11Opt.Split", ""]
    open(out, 'w').write("\n".join(L))
    print(f"wrote {out}: {len(cs)} cases", file=sys.stderr)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
