import pickle, itertools, sys, os
from fractions import Fraction as F
from geo import *
from banlp import facets, solve as banlp_solve
labels,V,D=pickle.load(open('dist.pkl','rb'))
cert,fc,T296=pickle.load(open('empty.pkl','rb'))
g4=sorted(pickle.load(open('greedy.pkl','rb')))
P=pickle.load(open('pairs.pkl','rb'))
N=len(labels)
M={999:(0,1,2,4,6,7,9,10,12,14,15),1462:(0,1,3,5,6,8,9,11,12,13,14),1659:(0,2,3,4,5,6,7,11,12,13,14)}
ht=lambda J: tuple(sorted(15-j for j in J))
six=sorted(set(M.values())|{ht(J) for J in M.values()})
diff=lambda a,b: all(a[g]!=b[g] for g in range(4))
OUT=sys.argv[1]
os.makedirs(OUT,exist_ok=True)
HDR="set_option linter.style.longLine false\n\nnamespace SquarePacking.S11Opt.Split\n\n"
FTR="\nend SquarePacking.S11Opt.Split\n"
def q(x):
    x=F(x)
    if x.denominator==1: return f"({x.numerator} : ℝ)"
    return f"({x.numerator} / {x.denominator} : ℝ)"
def lst(xs): return "["+", ".join(str(x) for x in xs)+"]"
def write(name,imports,doc,body):
    open(os.path.join(OUT,name),'w').write("".join(f"import {i}\n" for i in imports)+"\n/-!\n"+doc+"\n-/\n\n"+HDR+body+FTR)
# ---------- Data ----------
VP=list(itertools.combinations(range(4),2))
nb={}
for k,(g,h) in enumerate(VP):
    for a in range(16):
        nb[(k,a)]=[b for b in range(16) if P[(g,h,a,b)]]
nbD="["+", ".join("["+", ".join(lst(nb[(k,a)]) for a in range(16))+"]" for k in range(6))+"]"
fakes=sorted(fc)
banset={(i,j) for i,j in g4}
compat=[]
for r in range(N):
    m=0
    for s in range(N):
        if s!=r and diff(labels[r],labels[s]) and (min(r,s),max(r,s)) not in banset: m|=1<<s
    compat.append(m)
dom=[[(r,labels[r],compat[r]) for r in range(N) if labels[r][0]==o] for o in range(16)]
def ent(e): return f"({e[0]}, {lst(e[1])}, {e[2]})"
body=f"""/-- The 220 nonempty closed overlay regions (label tuples, lexicographic). -/
def regs : List (List ℕ) := {lst(lst(t) for t in labels)}

/-- The label of region `r` in view `g`. -/
def lab (r g : ℕ) : ℕ := (regs.getD r []).getD g 0

/-- The strict distance bans used by the search (region indices). -/
def banL : List (ℕ × ℕ) := {lst(f"({i}, {j})" for i,j in g4)}

/-- `compatM[r]` has bit `s` set iff the regions `r`, `s` have distinct labels in every view and are
not banned. -/
def compatM : List ℕ := {lst(compat)}

/-- The owner tables: the entries `(r, regs[r], compatM[r])` with `lab r 0 = o`. -/
def domT : List (List Entry) := {lst(lst(ent(e) for e in d) for d in dom)}

/-- The six raw masks of the candidates `999, 1462, 1659` and their half-turns. -/
def six : List (List ℕ) := {lst(lst(J) for J in six)}

/-- Pairwise partners: `nbL k a` lists the cells `b` of view `h` meeting the cell `a` of view `g`,
for the `k`-th view pair `(g, h)` in `(0,1), (0,2), (0,3), (1,2), (1,3), (2,3)`. -/
def nbD : List (List (List ℕ)) := {nbD}

def nbL (k a : ℕ) : List ℕ := (nbD.getD k []).getD a []

/-- The pairwise consistent label tuples that are empty (76). -/
def fakes : List (List ℕ) := {lst(lst(t) for t in fakes)}

lemma regs_length : regs.length = 220 := by decide +kernel

lemma compatM_length : compatM.length = 220 := by decide +kernel

lemma domT_eq : domT = (List.range 16).map fun o =>
    ((List.range 220).filter fun r => lab r 0 == o).map fun r => (r, regs.getD r [], compatM.getD r 0) := by
  decide +kernel

/-- Some view has equal labels. -/
def sameAny (t t' : List ℕ) : Bool := (List.range 4).any fun g => t.getD g 0 == t'.getD g 0

lemma compatM_ok : (List.range 220).all (fun r => (List.range 220).all fun s =>
    (compatM.getD r 0).testBit s || sameAny (regs.getD r []) (regs.getD s []) ||
      banL.contains (r, s) || banL.contains (s, r)) = true := by
  decide +kernel
"""
write("Data.lean",["Sqpack.S11Opt.Split.U3.Defs"],"# U3 — data: overlay regions, compatibility masks, owner tables\n\nGenerated by `scripts/u1u3/u3gen.py` from the sites `PU`; the region list is recomputed exactly there\n(stage counts 16, 56, 124, 220 as in the author's `cover_overlay_exact.json`).",body)
# ---------- helpers for facts ----------
def viewcell_facts(tag_list, pvar, hname):
    """tag list of constraints ('box',i) or ('cell',g,l,j); returns lines producing facts named, and names"""
    lines=[];names=[]
    for t in tag_list:
        if t[0]=='box':
            names.append(['bx0','bx1','by0','by1'][t[1]] if pvar=='p' else ['cx0','cx1','cy0','cy1'][t[1]])
        else:
            _,g,l,j=t
            nm=f"e{len(lines)}_{pvar}"
            xk,yk=PU[l]; xj,yj=PU[j]
            lines.append(f"have {nm} := cell_lin {hname(g,l)} {j} {q(xk)} {q(yk)} {q(xj)} {q(yj)} rfl rfl")
            names.append(nm)
    return lines,names
# ---------- pair emptiness ----------
VP=list(itertools.combinations(range(4),2))
def tagfact(t, hyp_of_view, var):
    """return (setup_lines, fact_name) for tag t"""
    if t[0]=='box':
        return [], ['bx0','bx1','by0','by1'][t[1]] if var=='p' else ['cx0','cx1','cy0','cy1'][t[1]]
    _,g,l,j=t
    xk,yk=PU[l]; xj,yj=PU[j]
    return [f"cell_lin {hyp_of_view(g)} {j} {q(xk)} {q(yk)} {q(xj)} {q(yj)} rfl rfl"], None
def box_setup(var,names):
    v=var
    return [f"obtain ⟨{names[0]}, {names[1]}, {names[2]}, {names[3]}⟩ := h{v}",
            f"unfold Ux at {names[1]} {names[3]}"]
def contra_lines(tags, hyp_of_view, ind):
    """lines deriving False from the given constraint tags (point p)"""
    pad=' '*ind; L=[]; used=[]
    k=0
    for t in tags:
        if t[0]=='box': used.append(['bx0','bx1','by0','by1'][t[1]]); continue
        _,g,l,j=t
        xk,yk=PU[l]; xj,yj=PU[j]
        L.append(f"{pad}have e{k} := cell_lin {hyp_of_view(g)} {j} {q(xk)} {q(yk)} {q(xj)} {q(yj)} rfl rfl")
        used.append(f"e{k}"); k+=1
    es=[u for u in used if u.startswith('e')]
    gs={t[1] for t in tags if t[0]=='cell'}
    if es: L.append(f"{pad}simp only [vw{', Ux' if gs & {1,2} else ''}] at {' '.join(es)}")
    L.append(f"{pad}linarith")
    return L
nb={}
for k,(g,h) in enumerate(VP):
    for a in range(16):
        nb[(k,a)]=[b for b in range(16) if P[(g,h,a,b)]]
nbD="["+", ".join("["+", ".join(lst(nb[(k,a)]) for a in range(16))+"]" for k in range(6))+"]"
for k,(g,h) in enumerate(VP):
    parts=[]
    for a in range(16):
        L=[f"lemma nb{g}{h}_{a} {{p : ℝ × ℝ}} (hp : InB p) (ha : InCellU {a} (vw {g} p)) {{b : ℕ}} (hb16 : b < 16)",
           f"    (hb : InCellU b (vw {h} p)) : b ∈ nbL {k} {a} := by",
           f"  obtain ⟨bx0, bx1, by0, by1⟩ := hp",
           f"  unfold Ux at bx1 by1",
           f"  change b ∈ {lst(nb[(k,a)])}",
           f"  interval_cases b"]
        for b in range(16):
            if P[(g,h,a,b)]:
                L.append("  · decide")
            else:
                tags=cert[(g,h,a,b)]
                body=contra_lines(tags, lambda vv: 'ha' if vv==g else 'hb', 4)
                L.append("  · exfalso")
                L+=body
        parts.append("\n".join(L))
    L=[f"lemma pair{g}{h} {{p : ℝ × ℝ}} (hp : InB p) {{a b : ℕ}} (ha16 : a < 16) (hb16 : b < 16)",
       f"    (ha : InCellU a (vw {g} p)) (hb : InCellU b (vw {h} p)) : b ∈ nbL {k} a := by",
       f"  interval_cases a"]
    for a in range(16): L.append(f"  · exact nb{g}{h}_{a} hp ha hb16 hb")
    parts.append("\n".join(L))
    write(f"Pair{g}{h}.lean",["Sqpack.S11Opt.Split.U3.Data"],f"# U3 — empty pairwise overlays, views {g} and {h}\n\nGenerated by `scripts/u1u3/u3gen.py`.  A point of `[1/2, Ux − 1/2]²` in the cell `a` of view {g} and\nthe cell `b` of view {h}: `b` is one of the listed partners of `a`.  Every other pair is empty, by\na Farkas certificate of at most three of the defining half-planes (`linarith`).","\n\n".join(parts)+"\n")
# ---------- fakes and membership ----------
parts=[]
for n,t in enumerate(fakes):
    usedv={x[1] for x in fc[t] if x[0]=='cell'}
    hn=[f"h{g}" if g in usedv else f"_h{g}" for g in range(4)]
    L=[f"lemma fake_{n} {{p : ℝ × ℝ}} (hp : InB p) ({hn[0]} : InCellU {t[0]} (vw 0 p)) ({hn[1]} : InCellU {t[1]} (vw 1 p))",
       f"    ({hn[2]} : InCellU {t[2]} (vw 2 p)) ({hn[3]} : InCellU {t[3]} (vw 3 p)) : False := by",
       f"  obtain ⟨bx0, bx1, by0, by1⟩ := hp",
       f"  unfold Ux at bx1 by1"]
    L+=contra_lines(fc[t], lambda vv: f'h{vv}', 2)
    parts.append("\n".join(L))
# fake dispatcher
L=["lemma not_fake {p : ℝ × ℝ} (hp : InB p) {a0 a1 a2 a3 : ℕ} (h0 : InCellU a0 (vw 0 p))",
   "    (h1 : InCellU a1 (vw 1 p)) (h2 : InCellU a2 (vw 2 p)) (h3 : InCellU a3 (vw 3 p))",
   "    (hf : [a0, a1, a2, a3] ∈ fakes) : False := by",
   "  simp only [fakes, List.mem_cons, List.cons.injEq, List.not_mem_nil, or_false, and_true] at hf",
   "  rcases hf with " + " | ".join("⟨rfl, rfl, rfl, rfl⟩" for _ in fakes)]
for n in range(len(fakes)): L.append(f"  · exact fake_{n} hp h0 h1 h2 h3")
parts.append("\n".join(L))
parts.append('''lemma combo_ok : (List.range 16).all (fun a0 => (nbL 0 a0).all fun a1 => (nbL 1 a0).all fun a2 =>
    (nbL 2 a0).all fun a3 => !((nbL 3 a1).contains a2 && (nbL 4 a1).contains a3 &&
      (nbL 5 a2).contains a3) || regs.contains [a0, a1, a2, a3] ||
        fakes.contains [a0, a1, a2, a3]) = true := by
  decide +kernel

/-- **Every centre lies in one of the 220 regions**: its four view labels form a listed tuple. -/
theorem tuple_mem {p : ℝ × ℝ} (hp : InB p) {a0 a1 a2 a3 : ℕ} (h016 : a0 < 16) (h116 : a1 < 16)
    (h216 : a2 < 16) (h316 : a3 < 16) (h0 : InCellU a0 (vw 0 p)) (h1 : InCellU a1 (vw 1 p))
    (h2 : InCellU a2 (vw 2 p)) (h3 : InCellU a3 (vw 3 p)) : [a0, a1, a2, a3] ∈ regs := by
  have m01 := pair01 hp h016 h116 h0 h1
  have m02 := pair02 hp h016 h216 h0 h2
  have m03 := pair03 hp h016 h316 h0 h3
  have m12 := pair12 hp h116 h216 h1 h2
  have m13 := pair13 hp h116 h316 h1 h3
  have m23 := pair23 hp h216 h316 h2 h3
  have := List.all_eq_true.mp (List.all_eq_true.mp (List.all_eq_true.mp (List.all_eq_true.mp
    combo_ok a0 (List.mem_range.mpr h016)) a1 m01) a2 m02) a3 m03
  have k1 : (nbL 3 a1).contains a2 = true := by simpa using m12
  have k2 : (nbL 4 a1).contains a3 = true := by simpa using m13
  have k3 : (nbL 5 a2).contains a3 = true := by simpa using m23
  rw [k1, k2, k3] at this
  simp only [Bool.and_self, Bool.not_true, Bool.false_or, Bool.or_eq_true] at this
  rcases this with h | h
  · simpa using h
  · exact (not_fake hp h0 h1 h2 h3 (by simpa using h)).elim''')
write("Mem.lean",[f"Sqpack.S11Opt.Split.U3.Pair{g}{h}" for g,h in VP],"# U3 — every centre lies in one of the 220 overlay regions\n\nGenerated by `scripts/u1u3/u3gen.py`.  The 76 pairwise consistent but empty label tuples are excluded by\nFarkas certificates of three half-planes each.","\n\n".join(parts)+"\n")
# ---------- bans ----------
def tag_of(ls,i):
    if i<4: return ('box',i)
    k=i-4; g=k//15; jj=k%15; l=ls[g]
    return ('cell',g,l,[j for j in range(16) if j!=l][jj])
parts=[]
for (r,s) in g4:
    Cr,ixr=facets(labels[r],V[r]); Cs,ixs=facets(labels[s],V[s])
    eps,sup=banlp_solve([Cr[t] for t in ixr],[Cs[t] for t in ixs])
    assert eps>1e-6
    tr=[tag_of(labels[r],t) for t in ixr]; ts=[tag_of(labels[s],t) for t in ixs]
    L=[f"/-- Regions {r} and {s} (squared distance at most {float(D[(r,s)]):.4f}). -/",
       f"theorem ban_{r}_{s} : BanT {lst(labels[r])} {lst(labels[s])} := by",
       "  intro p q hp hq hr hs",
       "  obtain ⟨bx0, bx1, by0, by1⟩ := hp",
       "  obtain ⟨cx0, cx1, cy0, cy1⟩ := hq",
       "  unfold Ux at bx1 by1 cx1 cy1"]
    for g in range(4):
        L.append(f"  have hr{g} : InCellU {labels[r][g]} (vw {g} p) := hr {g} (by norm_num)")
        L.append(f"  have hs{g} : InCellU {labels[s][g]} (vw {g} q) := hs {g} (by norm_num)")
    def facts(tags,var,hpre):
        names=[]
        for n,t in enumerate(tags):
            nm=f"{var}{n}"
            if t[0]=='box':
                i=t[1]; v1=f"{var}.1"; v2=f"{var}.2"
                expr=[f"{v1} - 1 / 2",f"387708359002281417731 / 10 ^ 20 - 1 / 2 - {v1}",f"{v2} - 1 / 2",f"387708359002281417731 / 10 ^ 20 - 1 / 2 - {v2}"][i]
                L.append(f"  have {nm} : (0 : ℝ) ≤ {expr} := by linarith")
            else:
                _,g,l,j=t; xk,yk=PU[l]; xj,yj=PU[j]
                L.append(f"  have {nm} := cell_lin {hpre}{g} {j} {q(xk)} {q(yk)} {q(xj)} {q(yj)} rfl rfl")
                L.append(f"  simp only [vw{', Ux' if g in (1,2) else ''}] at {nm}")
            names.append(nm)
        return names
    npn=facts(tr,'p','hr'); nqn=facts(ts,'q','hs')
    hints=[]
    for (kind,*ij),_ in sup:
        if kind=='pq': hints.append(f"mul_nonneg {npn[ij[0]]} {nqn[ij[1]]}")
        elif kind=='pp': hints.append(f"mul_nonneg {npn[ij[0]]} {npn[ij[1]]}")
        elif kind=='qq': hints.append(f"mul_nonneg {nqn[ij[0]]} {nqn[ij[1]]}")
        elif kind=='p': hints.append(npn[ij[0]])
        elif kind=='q': hints.append(nqn[ij[0]])
    L.append(f"  linarith [{', '.join(hints)}]")
    parts.append("\n".join(L))
L=["lemma banL_ok : ∀ x ∈ banL, BanT (regs.getD x.1 []) (regs.getD x.2 []) := by",
   "  intro x hx",
   "  simp only [banL, List.mem_cons, List.not_mem_nil, or_false] at hx",
   "  rcases hx with " + " | ".join("rfl" for _ in g4)]
for (r,s) in g4: L.append(f"  · exact ban_{r}_{s}")
parts.append("\n".join(L))
write("Ban.lean",["Sqpack.S11Opt.Split.U3.Data"],"# U3 — the strict distance bans used by the search\n\nGenerated by `scripts/u1u3/u3gen.py`.  Four of the author's 1,572 bans suffice for the search.  Each is a\ndegree-2 Handelman certificate on the product of the two regions (found by an LP, re-found exactly\nby `linarith`).","\n\n".join(parts)+"\n")
# ---------- search ----------
cnt={o:sum(1 for t in labels if t[0]==o) for o in range(16)}
gorder=sorted(range(16),key=lambda o:(cnt[o],o))
blocks=[]
for k,J in enumerate(six):
    blocks.append(f"""lemma search_{k} : six.all (fun M1 => six.all fun M2 => six.all fun M3 =>
    !ext domT [M1, M2, M3] (2 ^ 220 - 1) (ownerOrder.filter fun o => {lst(J)}.contains o)) = true := by
  decide +kernel""")
cases=[]
for k in range(len(six)):
    cases.append(f"""  · have := List.all_eq_true.mp (List.all_eq_true.mp (List.all_eq_true.mp search_{k} M1 h1) M2 h2) M3 h3
    exact Bool.eq_false_iff.mpr fun h => by rw [h] at this; exact absurd this (by decide)""")
body=f"""/-- The order in which the search visits owners (fewest regions first). -/
def ownerOrder : List ℕ := {lst(gorder)}

lemma ownerOrder_nodup : ownerOrder.Nodup := by decide

""" + "\n\n".join(blocks) + f"""

/-- **The finite assertion** (PROOF.md §6): for every identity-view mask `J₀` among the six raw
masks and every choice of target masks `M₁, M₂, M₃` for the views `1, 2, 3`, no pairwise compatible
choice of regions exists.  1,296 searches (28,636 nodes), checked by the kernel. -/
theorem search_unsat {{J0 M1 M2 M3 : List ℕ}} (h0 : J0 ∈ six) (h1 : M1 ∈ six) (h2 : M2 ∈ six)
    (h3 : M3 ∈ six) :
    ext domT [M1, M2, M3] (2 ^ 220 - 1) (ownerOrder.filter fun o => J0.contains o) = false := by
  simp only [six, List.mem_cons, List.not_mem_nil, or_false] at h0
  rcases h0 with {' | '.join('rfl' for _ in six)}
""" + "\n".join(cases) + "\n"
write("Search.lean",["Sqpack.S11Opt.Split.U3.Data"],"# U3 — the finite search of the D4 bridge\n\nOne kernel check per identity-view mask (216 target choices each).","\n"+body)
